### PR TITLE
[#13] Remove dead links from Footer

### LINKED ISSUE #13: Remove dead links from footer
# ALSO NEED TO REMOVE INSTA -- I didn't mark that on the screenshot

### PR DESCRIPTION
**Pull request by newswim**
Closes #13 

### After

image

### CODE REVIEW

**Comment by lianilychee** [comment]
LGTM

**Comment by lianilychee** [comment]
NVM my previous approval. I just realized that the "About" and "Contact us" links don't point anywhere..

Can "Contact us" open an email to info@open-austin.org?

Am ignoring "About" since it'll get sorted out when we declutter the nav

**Comment by attali-david** [comment]
Contact opens an email to info@open-austin.org. Did you want to add a subject line or message body?

**Review by attali-david — APPROVED** [review]

**Comment by lianilychee** [comment]
Yay! Nope, it's good to go. Thanks both, I'll merge now.

**Pull request merged**
