### PR TITLE
Compressed Assets

### PR DESCRIPTION
**Pull request by attali-david**

### CODE REVIEW

**Comment by newswim** [comment]
This seems reasonable, but I wonder if .png would be more appropriate for these, since they're all graphical.

**Comment by attali-david** [comment]
I converted the jpg to png. Compressing them reduced their size by a further 50%.

**Comment by lianilychee** [comment]
@newswim can David merge this?

**Comment by newswim** [comment]
@attali-david I noticed a few files were deleted, including a `logo-svg` -- were those not used anywhere?

**Review by newswim — APPROVED** [review]

**Pull request merged**
